services:
  mosquitto:
    image: eclipse-mosquitto:2.0.11
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "${MQTT_PORT}:1883"
      - "${WS_PORT}:9001"
    networks:
      - iot_network

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"
    depends_on:
      - mosquitto
    networks:
      - iot_network
    volumes:
      - node-red-data:/data
    restart: always

  nestjs-app:
    build: .
    container_name: nestjs-app
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_AT_SECRET=${JWT_AT_SECRET}
      - JWT_RT_SECRET=${JWT_RT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${APP_PORT}:3333"
    depends_on:
      - mosquitto
      - mariadb
    networks:
      - iot_network
    restart: always

  mariadb:
    image: mariadb:10
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mqtt
      - MYSQL_USER=prisma # not used
      - MYSQL_PASSWORD=prisma
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--connect']
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - mariadb:/data 
    networks:
      - iot_network

  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   restart: always
  #   command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
  #   environment:
  #     MONGO_INITDB_DATABASE: mqtt
  #     MONGO_REPLICA_HOST: localhost
  #     MONGO_REPLICA_PORT: "27017"
  #   volumes:
  #     - mongo-data:/data/db
  #   ports:
  #     - "${MONGO_PORT}:27017"
  #   networks:
  #     - iot_network

networks:
  iot_network:
    driver: bridge

volumes:
  node-red-data: {}
  mariadb: {}
  # mongo-data: {}
