version: "3.7"

services:

  mosquitto:
    image: eclipse-mosquitto:2.0.11
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "${MQTT_PORT}:1883"
      - "${WS_PORT}:9001"
    networks:
      - iot_network

  nestjs-app:
    build: .
    container_name: nestjs-app
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_AT_SECRET=${JWT_AT_SECRET}
      - JWT_RT_SECRET=${JWT_RT_SECRET}
      - DATABASE_URL=${DB_HOST}
    ports:
      - "${APP_PORT}:3333"
    depends_on:
      - mosquitto
      - mariadb
    networks:
      - iot_network
    restart: always

  mariadb:
    image: mariadb:10
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME} # not used
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - iot_network

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - nestjs-app
      - mariadb
      - mosquitto
    networks:
      - iot_network

networks:
  iot_network:
    driver: bridge

volumes:
  node-red-data: {}
  mariadb-data: {}
