{
 "title": "NodeJS Applications Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [
  "nodejs",
  "promethes"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info,app_kubernetes_io_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Memory Used mb",
   "type": "heatmap",
   "description": "Average memory used in megabytes",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes{app_kubernetes_io_name=~\"$instance\"} / 1024 / 1024) by(app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "NodeJS Version",
   "type": "stat",
   "description": "NodeJS Version",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nodejs_version_info{app_kubernetes_io_name=~\"$instance\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "bargauge",
   "description": "Process Restart Times Within Last 5 Minutes",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{app_kubernetes_io_name=~\"$instance\"}[$__range]))",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{app_kubernetes_io_name=~\"$instance\"}[2m]) * 100",
     "legendFormat": "User CPU - {{app_kubernetes_io_name}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{app_kubernetes_io_name=~\"$instance\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{app_kubernetes_io_name=~\"$instance\"}",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app_kubernetes_io_name=~\"$instance\"}",
     "legendFormat": "Process Memory - {{app_kubernetes_io_name}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{app_kubernetes_io_name=~\"$instance\"}",
     "legendFormat": "Heap Total - {{app_kubernetes_io_name}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{app_kubernetes_io_name=~\"$instance\"}",
     "legendFormat": "Heap Used - {{app_kubernetes_io_name}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{app_kubernetes_io_name=~\"$instance\"}",
     "legendFormat": "External Memory - {{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{app_kubernetes_io_name=~\"$instance\"}",
     "legendFormat": "Active Handler - {{app_kubernetes_io_name}}"
    },
    {
     "expr": "nodejs_active_requests_total{app_kubernetes_io_name=~\"$instance\"}",
     "legendFormat": "Active Request - {{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{app_kubernetes_io_name=~\"$instance\"}",
     "legendFormat": "Heap Total - {{app_kubernetes_io_name}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{app_kubernetes_io_name=~\"$instance\"}",
     "legendFormat": "Heap Used - {{app_kubernetes_io_name}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{app_kubernetes_io_name=~\"$instance\"}",
     "legendFormat": "Heap Used - {{app_kubernetes_io_name}} - {{space}}"
    }
   ]
  }
 ]
}